# loop example 1 it is old method and had limitations
-
   name: 'Create the users'
   hosts: localhost
   tasks:
     - user: name='{{ item }}' state=present
       loop:
         - user_name1
         - user_name2
         - user_name3
# loop example 1 it is old method and had limitations
   name: 'Create the users with uid'
   hosts: localhost
   tasks:
     - user: name='{{ item.name }}' state=present uid='{{ item.uid }}'
       loop:
         -
           name: user_name1
           uid: 1001
         -
           name: user_name2
           uid: 1002
         -
           name: user_name3
           uid: 1003

# with_items example 1 it will cross the limitations with_file with_url and so on
-
    name: 'Print list of fruits'
    hosts: localhost
    vars:
        fruits:
            - Apple
            - Banana
            - Grapes
            - Orange
    tasks:
        -
            command: 'echo "{{ item }}"'
            with_items: '{{ fruits }}'


# with_items example 2

-
    name: 'Install required packages'
    hosts: localhost
    vars:
        packages:
            - httpd
            - binutils
            - glibc
            - ksh
            - libaio
            - libXext
            - gcc
            - make
            - sysstat
            - unixODBC
            - mongodb
            - nodejs
            - grunt
    tasks:
        -
            yum: 'name={{ item }} state=present'
            with_items: '{{ packages }}'
